/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.0-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package service.rest.api;

import io.swagger.annotations.*;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import service.rest.dto.Flows;

import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-11-21T21:59:27.635+01:00")

@Api(value = "marketflow", description = "the marketflow API B")
public interface MarketflowApi {

    @ApiOperation(value = "get the market flow of selected company each minutes from the begining of the year 2017", nickname = "getCompanyCurrentMarketFlow", notes = "", response = Flows.class, responseContainer = "List", tags={ "Market Flow", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Flows.class, responseContainer = "List") })
    @RequestMapping(value = "/stockmarket/companycode/{companycode}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    List<Flows> getCompanyCurrentMarketFlow(@ApiParam(value = "Company code",required=true) @PathVariable("companycode") String companyCode);


}
