/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.0-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package service.rest.api;

import service.rest.dto.CompanyDto;
import service.rest.dto.CompanyFlowDto;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-11-21T21:59:27.635+01:00")

@Api(value = "marketflow", description = "the marketflow API")
public interface MarketflowApi {

    @ApiOperation(value = "get the market flow of selected company each minutes from the begining of the year 2017", nickname = "getCompanyCurrentMarketFlow", notes = "", response = CompanyFlowDto.class, responseContainer = "List", tags={ "Market Flow", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = CompanyFlowDto.class, responseContainer = "List") })
    @RequestMapping(value = "/marketflow/companies/{companyname}/fromcurrency/{fromcurrency}/tocurrency/{tocurrency}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<CompanyFlowDto>> getCompanyCurrentMarketFlow(@ApiParam(value = "Company name",required=true) @PathVariable("companyname") String companyname,@ApiParam(value = "initial currency code.",required=true) @PathVariable("fromcurrency") String fromcurrency,@ApiParam(value = "target currency code.",required=true) @PathVariable("tocurrency") String tocurrency);


    @ApiOperation(value = "get the list of all companies on the market", nickname = "getCurrentMarketCompany", notes = "", response = CompanyDto.class, responseContainer = "List", tags={ "Market", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = CompanyDto.class, responseContainer = "List") })
    @RequestMapping(value = "/marketflow/companies",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<CompanyDto>> getCurrentMarketCompany();

}
